@extends('layouts.app')

@section('title', "Edit $videogame->title")

@section('content')
    <h1 class="text-center mt-5">Edit videogame: {{ $videogame->title }}</h1>
    <form method="POST" action="{{ route('admin.videogames.update', $videogame) }}" class="text-white bg-dark p-5 rounded mt-5">
        @method('PUT')
        @csrf
<div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <input value="{{ old('title', $videogame->title) }}" type="text"
        class="form-control @error('title') is-invalid @enderror" id="title" aria-describedby="titleHelp"
        name="title" required>
    <div class="form-text">Required</div>
    @error('title')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
    @enderror
</div>
<div class="mb-3">
    <label for="slug" class="form-label">Videogame Slug</label>
    <input disabled value="{{ Str::slug(old('title', $videogame->title)) }}" type="text"
        class="form-control @error('slug') is-invalid @enderror" id="slug" aria-describedby="slugHelp"
        name="slug" required>
    <div class="form-text">Auto generated by the title</div>
</div>
<div class="mb-3">
    <label for="description" class="form-label">Description</label>
    <textarea class="form-control @error('description') is-invalid @enderror" name="description" id="description"
    rows="10">{{ old('description', $videogame->description) }}</textarea>
</div>
<div class="mb-3">
    <label for="image" class="form-label">Image (url)</label>
    <input value="{{ old('image', $videogame->image) }}" type="url"
    class="form-control @error('image') is-invalid @enderror" id="image" name="image">
    @error('image')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
    @enderror
</div>
<div class="mb-3">
    <label for="price" class="form-label">Price</label>
    <input value="{{ old('price', $videogame->price) }}" type="text"
        class="form-control @error('price') is-invalid @enderror" id="price" aria-describedby="priceHelp"
        name="price" required>
    <div class="form-text">Required</div>
    @error('price')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
    @enderror
</div>

<div class="mb-3 form-check">
    <label class="form-check-label" for="is_explicit">Explicit Content</label>
    <input type="checkbox" @if (old('is_explicit', $videogame->is_explicit)) checked @endif value="1"
        class="form-check-input @error('is_explicit') is-invalid @enderror" id="is_explicit" name="is_explicit">
</div>
<button type="submit" class="btn btn-success mt-3">Submit</button>
</form>
    <div class="d-flex justify-content-center my-5">
        <a href="{{ route('admin.videogames.show', $videogame) }}" class="btn btn-secondary">Go back</a>
    </div>
@endsection
@section('scripts')
    @vite('resources/js/slug-gen.js')
@endsection