@if ($videogame->exists)
    <h1 class="text-center mt-5">Edit videogame: {{ $videogame->title }}</h1>
    <form method="POST" action="{{ route('admin.videogames.update', $videogame) }}"
        class="text-white bg-dark p-5 rounded mt-5">
        @method('PUT')
    @else
        <form method="POST" action="{{ route('admin.videogames.store') }}" class="text-white bg-dark p-5 rounded mt-5">
@endif
@csrf

<div class="row">

    {{-- # Title --}}
    <div class="mb-3 col-6">
        <label for="title" class="form-label">Title</label>
        <input value="{{ old('title', $videogame->title) }}" type="text"
            class="form-control @error('title') is-invalid @enderror" id="title" aria-describedby="titleHelp"
            name="title" required>
        <div class="form-text">Required</div>
        @error('title')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror
    </div>

    {{-- # Slug --}}
    <div class="mb-3 col-6">
        <label for="slug" class="form-label">Videogame Slug</label>
        <input disabled value="{{ Str::slug(old('title', $videogame->title)) }}" type="text"
            class="form-control @error('slug') is-invalid @enderror" id="slug" aria-describedby="slugHelp"
            name="slug" required>
        <div class="form-text">Auto generated by the title</div>
    </div>

    {{-- # Description --}}
    <div class="mb-3 col-12">
        <label for="description" class="form-label">Description</label>
        <textarea class="form-control @error('description') is-invalid @enderror" name="description" id="description"
            rows="10">{{ old('description', $videogame->description) }}</textarea>
        @error('description')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror
    </div>

    {{-- # Image --}}
    <div class="col-11 mb-3">
        <label for="image" class="form-label">Url dell'immagine</label>
        <input type="url"class="form-control @error('image') is-invalid @enderror" id="image" name="image"
            value="{{ old('image', $videogame->image) }}" placeholder="Insersisci un url valido">
        @error('image')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror
    </div>

    {{-- # Image preview --}}
    <div class="col-1">
        <img src="{{ old('image', 'https://media.istockphoto.com/id/1147544807/vector/thumbnail-image-vector-graphic.jpg?s=612x612&w=0&k=20&c=rnCKVbdxqkjlcs3xH87-9gocETqpspHFXu5dIGB4wuM=') }}"
            alt="preview" class="img-fluid my-2" id="image-preview">
    </div>

    {{-- # Price --}}
    <div class="mb-3  ">
        <label for="price" class="form-label">Price</label>
        <input value="{{ old('price', $videogame->price) }}" type="text"
            class="form-control @error('price') is-invalid @enderror" id="price" aria-describedby="priceHelp"
            name="price" required>
        <div class="form-text">Required</div>
        @error('price')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror
    </div>

    {{-- # Explicit Content --}}
    <div class="mb-3 form-check">
        <label class="form-check-label" for="is_explicit">Explicit Content</label>
        <input type="checkbox" @if (old('is_explicit', $videogame->is_explicit)) checked @endif value="1"
            class="form-check-input @error('is_explicit') is-invalid @enderror" id="is_explicit" name="is_explicit">
    </div>

    <div class="d-flex align-items-center justify-content-between ">
        <a class="btn btn-secondary" href="{{ route('admin.videogames.index') }}">Go back</a>
        {{-- # Submit --}}
        <button type="submit" class="btn btn-success">Submit</button>
    </div>
</div>
</form>
